name: Build and Release Aseprite for Windows

on:
  push:
    branches:
      - main
    paths:
      - 'BuildLog.md'
env:
  BUILD_TYPE: Release

jobs:
  fetch-aseprite-info:
    name: Fetch Aseprite Info
    runs-on: windows-latest
    outputs:
      download-link: ${{ steps.aseprite-link.outputs.download-link }}
      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
    steps:
      - name: Fetch Aseprite 1.3.7 release link
        id: aseprite-link
        uses: a1393323447/fetch-release@main
        with:
            group: aseprite
            repo: aseprite
            match: Aseprite-v1.3.7-Source.zip

  create-release:
    name: Create Release
    runs-on: windows-latest
    needs: fetch-aseprite-info
    permissions:
      contents: write
    outputs:
      download-link: ${{ needs.fetch-aseprite-info.outputs.download-link }}
      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          body: Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aseprite:
    name: Build Aseprite
    needs: create-release
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Fetch Skia release link
        id: skia-link
        uses: a1393323447/fetch-release@main
        with:
            group: aseprite
            repo: skia
            match: Skia-Windows-Release-x64.zip
      - name: Download Skia
        run: |
          curl -o Skia-Windows-Release-x64.zip -L ${{ steps.skia-link.outputs.download-link }}
          7z x Skia-Windows-Release-x64.zip -oskia
      - name: Download Aseprite release
        run: |
          curl -o Aseprite-source.zip -L ${{ needs.create-release.outputs.download-link }}
          7z x Aseprite-source.zip -oaseprite
          mkdir -p aseprite/build
      - name: Set architecture for the produced binary (Windows)
        uses: ilammy/msvc-dev-cmd@v1
      - name: Run CMake (Windows)
        working-directory: aseprite/build
        shell: cmd
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_IGNORE_PATH='C:/ProgramData/chocolatey/bin/;C:/Strawberry/c/bin/' -DLAF_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 -G Ninja ..
      - name: Run Ninja
        working-directory: aseprite/build
        run: ninja aseprite
      - name: Clean up build
        working-directory: aseprite/build/bin
        shell: bash
        run: rm -f gen modp_b64_gen gen.exe gen.exe.manifest modp_b64_gen.exe modp_b64_gen.exe.manifest
      - name: Make portable zip
        working-directory: aseprite/build/bin
        run: echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini
      - name: Create release zip
        working-directory: aseprite/build/bin
        run: 7z -tzip a Aseprite-${{ needs.create-release.outputs.release-tag }}-windows.zip *
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-windows.zip
          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-windows.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
